import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { aiService } from "../ai/services/AIService";
import { CustomAIRequestOptions } from "../ai/factory/ProviderFactory";
import { safeAutoTable, getAutoTableFinalY } from "../utils/pdfExport";

// ==========================================
// 1. TRI & PSYCHOMETRIC CALIBRATION TYPES
// ==========================================
export interface ItemSubmissionStat {
  studentId: string;
  studentAbilityScore: number; // 0 - 100
  isCorrect: boolean;
  timeSpentSeconds: number;
}

export interface ItemTriMetrics {
  itemId: string;
  itemTitle: string;
  difficultyParamB: number; // -3.0 (muito fácil) a +3.0 (muito difícil)
  discriminationParamA: number; // 0.0 (sem discriminação) a 2.5+ (alta discriminação)
  guessingParamC: number; // 0.0 a 0.35
  successRatePercentage: number; // 0 - 100%
  pointBiserialCorrelation: number; // -1.0 a +1.0
  totalAttempts: number;
  qualityStatus: "EXCELENTE" | "ADEQUADO" | "REQUER_REVISAO" | "ITEM_DEFEITUOSO_AMBIGUO";
  diagnosticRecommendation: string;
}

// ==========================================
// 2. DIAGNOSTIC MCQ (DISTRACTOR ENGINEERING)
// ==========================================
export interface DiagnosticOption {
  optionLetter: "A" | "B" | "C" | "D" | "E";
  text: string;
  isCorrect: boolean;
  misconceptionDiagnosed: string; // Qual erro de raciocínio essa alternativa revela
  pedagogicalIntervention: string; // O que o professor deve explicar se o aluno marcou essa
}

export interface DiagnosticMcqQuestion {
  id: string;
  topic: string;
  subtopic: string;
  bloomLevel: string;
  contextScenario: string;
  questionStem: string;
  codeSnippet?: string;
  options: DiagnosticOption[];
  conceptualExplanation: string;
  saepCompetencyTag: string;
  createdAt: string;
}

// ==========================================
// 3. PARAMETRIC POLIMORPHIC ANTI-CHEAT
// ==========================================
export interface ParametricSeedInstance {
  seedId: string;
  studentNameOrId: string;
  parameters: Record<string, string | number>;
  renderedStatement: string;
  expectedResult: string | number;
  testCases: Array<{ input: string; expectedOutput: string; isHidden: boolean }>;
  verificationHash: string;
}

export interface ParametricQuestionTemplate {
  templateId: string;
  title: string;
  baseScenario: string;
  variableDefinitions: Array<{ name: string; type: "number" | "choice" | "dataset"; rangeOrValues: string }>;
  formulaOrLogicDescription: string;
  sampleInstances: ParametricSeedInstance[];
  createdAt: string;
}

// ==========================================
// 4. OCR & MULTI-SOURCE INGESTION
// ==========================================
export interface IngestedParsedItem {
  id: string;
  extractedTitle: string;
  questionType: "MULTIPLA_ESCOLHA" | "CODIGO_DISCURSIVA" | "SQL_BANCO" | "VERDADEIRO_FALSO";
  contextScenario: string;
  commandText: string;
  options?: string[];
  correctAnswerOrCriterion: string;
  autoGeneratedTestCases?: Array<{ input: string; expectedOutput: string; description: string }>;
  saepTargetCompetency: string;
  confidenceScore: number; // 0 - 100
}

// ==========================================
// 5. SMART EXAM ASSEMBLER (VERSIONS A/B/C/D)
// ==========================================
export interface AssembledExamItem {
  itemNumber: number;
  originalId: string;
  title: string;
  type: string;
  difficulty: "Fácil" | "Médio" | "Difícil";
  statement: string;
  options?: Array<{ letter: string; text: string }>;
  correctAnswer: string;
  points: number;
}

export interface AssembledExamBooklet {
  versionLetter: "A" | "B" | "C" | "D";
  examTitle: string;
  courseName: string;
  classId: string;
  durationMinutes: number;
  totalPoints: number;
  items: AssembledExamItem[];
  answerKeyMatrix: Array<{ itemNumber: number; correctOptionOrSummary: string; points: number }>;
}

// ==========================================
// 6. CODE BUG HUNT & REFACTORING LAB
// ==========================================
export interface IntentionalBugDetail {
  bugId: string;
  bugType: "SECURITY_VULNERABILITY" | "CONCURRENCY_RACE" | "OFF_BY_ONE" | "RESOURCE_LEAK" | "TRANSACTION_INTEGRITY";
  locationHint: string;
  explanation: string;
  fixSolution: string;
}

export interface CodeBugHuntChallenge {
  id: string;
  title: string;
  language: string;
  scenario: string;
  buggySourceCode: string;
  totalBugsCount: number;
  bugsCatalog: IntentionalBugDetail[];
  regressionTestCases: Array<{ id: number; input: string; expectedOutput: string; catchesBugId: string }>;
  refactoredGoldenSolution: string;
  rubricCriteria: Array<{ criterion: string; weight: number }>;
  createdAt: string;
}

export class AdvancedItemBankService {
  // =========================================================================
  // 1. TRI & PSYCHOMETRIC CALIBRATION ENGINE
  // =========================================================================
  static calculateItemTriMetrics(params: {
    itemId: string;
    itemTitle: string;
    submissions: ItemSubmissionStat[];
  }): ItemTriMetrics {
    const subs = params.submissions || [];
    const totalAttempts = subs.length;

    if (totalAttempts === 0) {
      return {
        itemId: params.itemId,
        itemTitle: params.itemTitle,
        difficultyParamB: 0.0,
        discriminationParamA: 1.0,
        guessingParamC: 0.2,
        successRatePercentage: 50,
        pointBiserialCorrelation: 0.4,
        totalAttempts: 0,
        qualityStatus: "ADEQUADO",
        diagnosticRecommendation: "Item sem submissões registradas. Aguardando calibração empírica."
      };
    }

    const correctCount = subs.filter(s => s.isCorrect).length;
    const successRate = (correctCount / totalAttempts) * 100;

    // Parâmetro b (Dificuldade): b = -ln(p / (1 - p)) mapeado entre -3.0 e +3.0
    const p = Math.max(0.01, Math.min(0.99, correctCount / totalAttempts));
    let paramB = -Math.log(p / (1 - p));
    paramB = Math.round(Math.max(-3.0, Math.min(3.0, paramB)) * 100) / 100;

    // Correlação Ponto Bisserial (r_pbi) entre acerto no item e habilidade geral do aluno
    const avgScoreTotal = subs.reduce((acc, s) => acc + s.studentAbilityScore, 0) / totalAttempts;
    const correctSubs = subs.filter(s => s.isCorrect);
    const avgScoreCorrect = correctSubs.length > 0
      ? correctSubs.reduce((acc, s) => acc + s.studentAbilityScore, 0) / correctSubs.length
      : avgScoreTotal;

    const variance = subs.reduce((acc, s) => acc + Math.pow(s.studentAbilityScore - avgScoreTotal, 2), 0) / totalAttempts;
    const stdDev = Math.sqrt(variance) || 1.0;

    const rPbi = (stdDev > 0 && correctCount > 0 && correctCount < totalAttempts)
      ? ((avgScoreCorrect - avgScoreTotal) / stdDev) * Math.sqrt((p * (1 - p)))
      : 0.45;

    const cleanRPbi = Math.round(Math.max(-1.0, Math.min(1.0, rPbi)) * 100) / 100;

    // Parâmetro a (Discriminação): proporcional à correlação bisserial
    let paramA = Math.round((Math.max(0.1, cleanRPbi * 2.2)) * 100) / 100;
    if (cleanRPbi <= 0) paramA = 0.05;

    // Parâmetro c (Adivinhação baseada em taxa de acerto de alunos de baixa proficiência)
    const lowAbilitySubs = subs.filter(s => s.studentAbilityScore < 40);
    const lowAbilityCorrect = lowAbilitySubs.filter(s => s.isCorrect).length;
    const paramC = lowAbilitySubs.length > 0
      ? Math.round((lowAbilityCorrect / lowAbilitySubs.length) * 100) / 100
      : 0.20;

    // Determinar Status de Qualidade Psicométrica
    let status: "EXCELENTE" | "ADEQUADO" | "REQUER_REVISAO" | "ITEM_DEFEITUOSO_AMBIGUO" = "ADEQUADO";
    let recommendation = "Item calibrado e pronto para montagem de provas balanceadas.";

    if (cleanRPbi < 0.15 || paramA < 0.3) {
      status = "ITEM_DEFEITUOSO_AMBIGUO";
      recommendation = "Alerta Crítico: Item com discriminação nula ou negativa. Alunos de alta proficiência estão errando mais que os de baixa proficiência (provável ambiguidade de enunciado ou gabarito invertido).";
    } else if (cleanRPbi < 0.30 || successRate < 15 || successRate > 92) {
      status = "REQUER_REVISAO";
      recommendation = successRate < 15
        ? "Item excessivamente difícil. Avaliar se os pré-requisitos foram cobertos em aula."
        : successRate > 92
        ? "Item com baixíssimo poder discriminatório (quase todos acertam). Sugere-se enriquecer com casos de borda."
        : "Item com correlação limítrofe. Recomenda-se ajustar distratores.";
    } else if (paramA >= 1.2 && cleanRPbi >= 0.40) {
      status = "EXCELENTE";
      recommendation = "Item de altíssima precisão psicométrica. Excelente para diferenciar alunos adequados de avançados no SAEP.";
    }

    return {
      itemId: params.itemId,
      itemTitle: params.itemTitle,
      difficultyParamB: paramB,
      discriminationParamA: paramA,
      guessingParamC: paramC,
      successRatePercentage: Math.round(successRate * 10) / 10,
      pointBiserialCorrelation: cleanRPbi,
      totalAttempts,
      qualityStatus: status,
      diagnosticRecommendation: recommendation
    };
  }

  // =========================================================================
  // 2. DIAGNOSTIC MCQ GENERATOR (DISTRACTOR COGNITIVE ENGINEERING)
  // =========================================================================
  static async generateDiagnosticMcq(params: {
    topic: string;
    subtopic?: string;
    bloomLevel?: string;
    targetCompetency?: string;
    providerConfig?: CustomAIRequestOptions;
  }): Promise<DiagnosticMcqQuestion> {
    const id = `mcq_diag_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const topic = params.topic || "Lógica de Programação e Algoritmos";
    const subtopic = params.subtopic || "Recursão e Controle de Pilha";
    const bloomLevel = params.bloomLevel || "Análise / Diagnóstico";
    const competency = params.targetCompetency || "Desenvolver algoritmos com eficiência e controle de memória";

    const hasAI = !!(process.env.GEMINI_API_KEY || process.env.AI_PROVIDER || params.providerConfig?.apiKey);

    if (hasAI) {
      try {
        const schema = {
          type: "OBJECT",
          properties: {
            contextScenario: { type: "STRING" },
            questionStem: { type: "STRING" },
            codeSnippet: { type: "STRING" },
            options: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  optionLetter: { type: "STRING", enum: ["A", "B", "C", "D", "E"] },
                  text: { type: "STRING" },
                  isCorrect: { type: "BOOLEAN" },
                  misconceptionDiagnosed: { type: "STRING", description: "Equívoco conceitual específico revelado por esta alternativa" },
                  pedagogicalIntervention: { type: "STRING", description: "Instrução de remediação para o professor aplicar" }
                },
                required: ["optionLetter", "text", "isCorrect", "misconceptionDiagnosed", "pedagogicalIntervention"]
              }
            },
            conceptualExplanation: { type: "STRING" },
            saepCompetencyTag: { type: "STRING" }
          },
          required: ["contextScenario", "questionStem", "options", "conceptualExplanation"]
        };

        const optConfig = {
          systemInstruction: "Você é um Psicometrista Educacional e Arquiteto de Itens do SENAI. Gere uma questão de Múltipla Escolha Diagnóstica onde CADA distrator (alternativa errada) seja uma armadilha cognitiva mapeada para uma falha conceitual real do estudante.",
          providerConfig: params.providerConfig
        };

        const promptText = `
Gere uma questão de Múltipla Escolha Diagnóstica de alta precisão:
Tema: ${topic}
Subtópico: ${subtopic}
Taxonomia de Bloom: ${bloomLevel}
Competência SAEP: ${competency}

Certifique-se de que:
1. Exatamente 1 alternativa seja correta.
2. Cada uma das outras 4 alternativas incorretas capture um erro típico comprovado de estudantes (ex: confusão de escopo, off-by-one, erro de ponteiro, falso positivo de concorrência).
`;

        const payload = await aiService.generateStructuredWithRetry<any>(promptText, schema, optConfig);
        if (payload && Array.isArray(payload.options) && payload.options.length >= 4) {
          return {
            id,
            topic,
            subtopic,
            bloomLevel,
            contextScenario: payload.contextScenario || "Cenário industrial aplicado.",
            questionStem: payload.questionStem,
            codeSnippet: payload.codeSnippet,
            options: payload.options,
            conceptualExplanation: payload.conceptualExplanation,
            saepCompetencyTag: payload.saepCompetencyTag || competency,
            createdAt: new Date().toISOString()
          };
        }
      } catch (err: any) {
        console.warn("[AdvancedItemBankService] MCQ AI fallback:", err.message);
      }
    }

    // Heuristic Fallback
    return {
      id,
      topic,
      subtopic,
      bloomLevel,
      contextScenario: "Em uma aplicação de monitoramento logístico, um microsserviço precisa processar lotes de pacotes com fila FIFO recursiva.",
      questionStem: "Considere a função recursiva abaixo. Qual será o retorno ao processar a lista [10, 20, 30] e qual é o impacto no consumo de pilha de execução?",
      codeSnippet: `function somarFila(lote: number[]): number {\n  if (lote.length === 0) return 0;\n  return lote[0] + somarFila(lote.slice(1));\n}`,
      options: [
        {
          optionLetter: "A",
          text: "Retorna 60 e consome O(n) de memória na call stack, criando novas cópias de array a cada chamada com slice.",
          isCorrect: true,
          misconceptionDiagnosed: "Compreensão exata de corretude algorítmica e complexidade de espaço.",
          pedagogicalIntervention: "Estudante dominou o conceito. Pode avançar para otimização com Tail Call Optimization ou iterativo."
        },
        {
          optionLetter: "B",
          text: "Retorna 60 e consome O(1) de memória, pois a recursão é convertida automaticamente em loop pelo interpretador.",
          isCorrect: false,
          misconceptionDiagnosed: "Crença equivocada de que todo interpretador realiza Tail Call Elimination implícita sem ponteiros de acumulador.",
          pedagogicalIntervention: "Revisar o ciclo de vida do Stack Frame e o custo de chamadas recursivas sem TCO."
        },
        {
          optionLetter: "C",
          text: "Retorna 30, pois o método slice(1) remove o primeiro elemento de forma mutável no array original.",
          isCorrect: false,
          misconceptionDiagnosed: "Confusão entre métodos imutáveis (slice) e mutáveis (splice) de manipulação de listas.",
          pedagogicalIntervention: "Praticar a diferença fundamental entre operações funcionais imutáveis vs métodos que alteram a referência in-place."
        },
        {
          optionLetter: "D",
          text: "Entra em loop infinito (Stack Overflow), pois a condição de parada verifica lote.length === 0 em vez de lote.length === 1.",
          isCorrect: false,
          misconceptionDiagnosed: "Dificuldade na identificação do caso base recursivo e contagem de limites de parada.",
          pedagogicalIntervention: "Executar o teste de mesa passo a passo desenhando o estado da árvore recursiva para listas vazias."
        },
        {
          optionLetter: "E",
          text: "Retorna 10, processando apenas a cabeça da lista e ignorando as chamadas subsequentes.",
          isCorrect: false,
          misconceptionDiagnosed: "Falta de compreensão do encadeamento de retornos e retorno de expressão composta.",
          pedagogicalIntervention: "Demonstrar o fluxo de 'ida' e 'volta' da pilha recursiva com depuração com breakpoints."
        }
      ],
      conceptualExplanation: "A função soma recursivamente os elementos retornando 60. Cada invocação cria um novo subarray via slice(1), gerando complexidade de espaço O(n) tanto de pilha quanto de alocação de memória.",
      saepCompetencyTag: competency,
      createdAt: new Date().toISOString()
    };
  }

  // =========================================================================
  // 3. PARAMETRIC POLIMORPHIC GENERATOR (ANTI-CHEAT ENGINE)
  // =========================================================================
  static generateParametricInstances(params: {
    title: string;
    scenarioTemplate: string;
    studentList: Array<{ id: string; name: string }>;
    formulaType: "FINANCE_INTEREST" | "SHIPPING_WEIGHT" | "ARRAY_ANOMALY" | "SQL_DISCOUNT";
  }): ParametricQuestionTemplate {
    const templateId = `param_tmpl_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const instances: ParametricSeedInstance[] = [];

    params.studentList.forEach((st, idx) => {
      // Gera semente pseudo-aleatória determinística baseada no ID do estudante
      const seedVal = Math.abs(st.id.split("").reduce((acc, c) => acc + c.charCodeAt(0), 0) + (idx * 37)) % 1000;
      
      let renderedStatement = "";
      let expectedResult: string | number = "";
      let testCases: Array<{ input: string; expectedOutput: string; isHidden: boolean }> = [];
      const parameters: Record<string, string | number> = {};

      if (params.formulaType === "FINANCE_INTEREST") {
        const capital = 1000 + (seedVal % 15) * 500;
        const taxa = 2 + (seedVal % 7);
        const meses = 3 + (seedVal % 10);
        const total = Math.round((capital * Math.pow(1 + taxa / 100, meses)) * 100) / 100;

        parameters.capital = capital;
        parameters.taxa = taxa;
        parameters.meses = meses;

        renderedStatement = `Uma fintech contratou você para calcular o montante de um investimento inicial de R$ ${capital},00 com taxa composta de ${taxa}% ao mês durante ${meses} meses. Escreva a função calcularMontante(c, i, t) que retorne o valor final arredondado em 2 casas decimais.`;
        expectedResult = total;

        testCases = [
          { input: `[${capital}, ${taxa}, ${meses}]`, expectedOutput: `${total}`, isHidden: false },
          { input: `[${capital}, ${taxa}, 0]`, expectedOutput: `${capital}.00`, isHidden: false },
          { input: `[${capital * 2}, ${taxa}, ${meses}]`, expectedOutput: `${(total * 2).toFixed(2)}`, isHidden: true }
        ];
      } else if (params.formulaType === "SHIPPING_WEIGHT") {
        const pesoBase = 5 + (seedVal % 20);
        const tarifaKg = 12 + (seedVal % 8);
        const taxaUrgente = 25 + (seedVal % 15);
        const custoPadrao = (pesoBase * tarifaKg);
        const custoUrgente = custoPadrao + taxaUrgente;

        parameters.peso = pesoBase;
        parameters.tarifaKg = tarifaKg;
        parameters.taxaUrgente = taxaUrgente;

        renderedStatement = `Para um operador logístico, calcule o frete de uma carga de ${pesoBase}kg com tarifa de R$ ${tarifaKg}/kg e taxa de entrega expressa de R$ ${taxaUrgente}. Retorne um objeto com { padrao: ${custoPadrao}, expressa: ${custoUrgente} }.`;
        expectedResult = JSON.stringify({ padrao: custoPadrao, expressa: custoUrgente });

        testCases = [
          { input: `[${pesoBase}, ${tarifaKg}, ${taxaUrgente}]`, expectedOutput: JSON.stringify({ padrao: custoPadrao, expressa: custoUrgente }), isHidden: false },
          { input: `[0, ${tarifaKg}, ${taxaUrgente}]`, expectedOutput: JSON.stringify({ padrao: 0, expressa: taxaUrgente }), isHidden: true }
        ];
      } else {
        const threshold = 50 + (seedVal % 40);
        parameters.threshold = threshold;

        renderedStatement = `Crie uma função filtrarSensores(leituras, limite = ${threshold}) que receba um array de telemetria e retorne apenas os valores estritamente maiores que ${threshold}, ordenados de forma decrescente.`;
        expectedResult = `[${threshold + 10}, ${threshold + 5}]`;

        testCases = [
          { input: `[[${threshold - 5}, ${threshold + 5}, ${threshold + 10}], ${threshold}]`, expectedOutput: `[${threshold + 10}, ${threshold + 5}]`, isHidden: false },
          { input: `[[], ${threshold}]`, expectedOutput: `[]`, isHidden: true }
        ];
      }

      const verificationHash = `vhash_${Math.random().toString(36).substring(2, 8)}_${seedVal}`;

      instances.push({
        seedId: `seed_${st.id}`,
        studentNameOrId: st.name || st.id,
        parameters,
        renderedStatement,
        expectedResult,
        testCases,
        verificationHash
      });
    });

    return {
      templateId,
      title: params.title || "Questão Parametrizada Anti-Cola",
      baseScenario: params.scenarioTemplate || "Template dinâmico com semente exclusiva por aluno.",
      variableDefinitions: [
        { name: "var1", type: "number", rangeOrValues: "10-100" },
        { name: "var2", type: "number", rangeOrValues: "2-15" }
      ],
      formulaOrLogicDescription: "Geração polimórfica de casos de teste com determinismo por hash de matrícula.",
      sampleInstances: instances,
      createdAt: new Date().toISOString()
    };
  }

  // =========================================================================
  // 4. OCR & MULTI-SOURCE INGESTION ENGINE
  // =========================================================================
  static async ingestMultiSourceExam(params: {
    rawTextOrOcr: string;
    sourceType?: "FOTO_OCR" | "PDF_PROVA" | "MOODLE_XML" | "WORD_DOC";
    targetCourse?: string;
    providerConfig?: CustomAIRequestOptions;
  }): Promise<{ totalIngested: number; items: IngestedParsedItem[] }> {
    const raw = (params.rawTextOrOcr || "").trim();
    if (!raw) {
      return { totalIngested: 0, items: [] };
    }

    const hasAI = !!(process.env.GEMINI_API_KEY || process.env.AI_PROVIDER || params.providerConfig?.apiKey);

    if (hasAI) {
      try {
        const schema = {
          type: "OBJECT",
          properties: {
            items: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  extractedTitle: { type: "STRING" },
                  questionType: { type: "STRING", enum: ["MULTIPLA_ESCOLHA", "CODIGO_DISCURSIVA", "SQL_BANCO", "VERDADEIRO_FALSO"] },
                  contextScenario: { type: "STRING" },
                  commandText: { type: "STRING" },
                  options: { type: "ARRAY", items: { type: "STRING" } },
                  correctAnswerOrCriterion: { type: "STRING" },
                  autoGeneratedTestCases: {
                    type: "ARRAY",
                    items: {
                      type: "OBJECT",
                      properties: {
                        input: { type: "STRING" },
                        expectedOutput: { type: "STRING" },
                        description: { type: "STRING" }
                      },
                      required: ["input", "expectedOutput", "description"]
                    }
                  },
                  saepTargetCompetency: { type: "STRING" },
                  confidenceScore: { type: "INTEGER" }
                },
                required: ["extractedTitle", "questionType", "commandText", "correctAnswerOrCriterion", "confidenceScore"]
              }
            }
          },
          required: ["items"]
        };

        const optConfig = {
          systemInstruction: "Você é um especialista em OCR, Processamento de Linguagem Natural e Ingestão de Provas do SENAI. Receba o texto bruto de uma prova/lista de exercícios e fragmente em questões estruturadas com casos de teste automatizados e alinhamento com a matriz SAEP.",
          providerConfig: params.providerConfig
        };

        const promptText = `
Faça o parsing, segmentação e geração de testes das questões presentes no seguinte documento/OCR:
Origem: ${params.sourceType || "PDF_PROVA"}
Curso Alvo: ${params.targetCourse || "Desenvolvimento de Sistemas"}

Conteúdo Bruto:
"""
${raw.substring(0, 8000)}
"""
`;

        const payload = await aiService.generateStructuredWithRetry<any>(promptText, schema, optConfig);
        if (payload && Array.isArray(payload.items) && payload.items.length > 0) {
          const formatted = payload.items.map((item: any, idx: number) => ({
            id: `ingested_${Date.now()}_${idx + 1}`,
            extractedTitle: item.extractedTitle || `Questão ${idx + 1}`,
            questionType: item.questionType || "CODIGO_DISCURSIVA",
            contextScenario: item.contextScenario || "Cenário extraído do documento original.",
            commandText: item.commandText || "Implemente a solução solicitada.",
            options: Array.isArray(item.options) ? item.options : undefined,
            correctAnswerOrCriterion: item.correctAnswerOrCriterion || "Gabarito de referência.",
            autoGeneratedTestCases: Array.isArray(item.autoGeneratedTestCases) ? item.autoGeneratedTestCases : [
              { input: "input_teste", expectedOutput: "output_esperado", description: "Caso de validação geral" }
            ],
            saepTargetCompetency: item.saepTargetCompetency || "Lógica e Construção de Algoritmos",
            confidenceScore: Number(item.confidenceScore) || 90
          }));

          return { totalIngested: formatted.length, items: formatted };
        }
      } catch (err: any) {
        console.warn("[AdvancedItemBankService] OCR Ingest AI fallback:", err.message);
      }
    }

    // Heuristic Segmenter Fallback
    const lines = raw.split("\n").filter(l => l.trim().length > 0);
    const mockItem: IngestedParsedItem = {
      id: `ingested_${Date.now()}_1`,
      extractedTitle: lines[0] ? lines[0].substring(0, 60) : "Questão Ingerida do Documento",
      questionType: "CODIGO_DISCURSIVA",
      contextScenario: "Exercício extraído automaticamente por parsing heurístico do arquivo fornecido.",
      commandText: lines.slice(0, 4).join(" "),
      correctAnswerOrCriterion: "Código que atenda aos requisitos funcionais descritos.",
      autoGeneratedTestCases: [
        { input: "[10, 20]", expectedOutput: "30", description: "Teste de fluxo padrão" },
        { input: "[]", expectedOutput: "0", description: "Teste de caso de borda vazio" }
      ],
      saepTargetCompetency: "Construção e Validação de Algoritmos",
      confidenceScore: 85
    };

    return { totalIngested: 1, items: [mockItem] };
  }

  // =========================================================================
  // 5. SMART EXAM ASSEMBLER (4 BOOKLETS A, B, C, D WITH ROTATION)
  // =========================================================================
  static assembleBalancedExam(params: {
    examTitle: string;
    courseName: string;
    classId: string;
    durationMinutes?: number;
    distribution: { easyPct: number; mediumPct: number; hardPct: number };
    availableBankItems: Array<{
      id: string;
      title: string;
      type: string;
      difficulty: "Fácil" | "Médio" | "Difícil";
      statement: string;
      options?: Array<{ letter: string; text: string }>;
      correctAnswer: string;
      points?: number;
    }>;
  }): AssembledExamBooklet[] {
    const items = [...params.availableBankItems];
    const duration = params.durationMinutes || 90;
    const versions: Array<"A" | "B" | "C" | "D"> = ["A", "B", "C", "D"];

    // Embaralhamento determinístico por versão
    return versions.map((versionLetter, vIdx) => {
      // Cria uma cópia com rotação/embaralhamento baseado no índice da versão
      const rotatedItems = [...items].sort((a, b) => {
        const hashA = (a.id + versionLetter).split("").reduce((acc, c) => acc + c.charCodeAt(0), 0);
        const hashB = (b.id + versionLetter).split("").reduce((acc, c) => acc + c.charCodeAt(0), 0);
        return hashA - hashB;
      });

      const assembledItems: AssembledExamItem[] = rotatedItems.map((it, idx) => {
        let rotatedOptions = it.options ? [...it.options] : undefined;
        let newCorrectAnswer = it.correctAnswer;

        // Para múltipla escolha, rotaciona as alternativas também
        if (rotatedOptions && rotatedOptions.length > 0) {
          const opts = rotatedOptions;
          const correctOpt = opts.find(o => o.letter === it.correctAnswer || o.text === it.correctAnswer);
          const letters = ["A", "B", "C", "D", "E"].slice(0, opts.length);
          
          // Permuta alternativas conforme a versão
          const shift = (vIdx + idx) % opts.length;
          const permuted = opts.map((_, i) => opts[(i + shift) % opts.length]);
          
          rotatedOptions = permuted.map((opt, i) => ({
            letter: letters[i],
            text: opt.text
          }));

          if (correctOpt) {
            const foundIndex = permuted.findIndex(p => p.text === correctOpt.text);
            newCorrectAnswer = foundIndex !== -1 ? letters[foundIndex] : "A";
          }
        }

        return {
          itemNumber: idx + 1,
          originalId: it.id,
          title: it.title,
          type: it.type,
          difficulty: it.difficulty,
          statement: it.statement,
          options: rotatedOptions,
          correctAnswer: newCorrectAnswer,
          points: it.points || Math.round(100 / Math.max(1, rotatedItems.length))
        };
      });

      const answerKey = assembledItems.map(it => ({
        itemNumber: it.itemNumber,
        correctOptionOrSummary: it.options ? it.correctAnswer : it.correctAnswer.substring(0, 40),
        points: it.points
      }));

      const totalPoints = assembledItems.reduce((acc, it) => acc + it.points, 0);

      return {
        versionLetter,
        examTitle: params.examTitle,
        courseName: params.courseName,
        classId: params.classId,
        durationMinutes: duration,
        totalPoints,
        items: assembledItems,
        answerKeyMatrix: answerKey
      };
    });
  }

  // =========================================================================
  // 6. CODE BUG HUNT & REFACTORING LAB ENGINE
  // =========================================================================
  static async generateBugHuntChallenge(params: {
    topic: string;
    language?: string;
    targetedBugTypes?: Array<"SECURITY_VULNERABILITY" | "CONCURRENCY_RACE" | "OFF_BY_ONE" | "RESOURCE_LEAK" | "TRANSACTION_INTEGRITY">;
    providerConfig?: CustomAIRequestOptions;
  }): Promise<CodeBugHuntChallenge> {
    const id = `bughunt_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const topic = params.topic || "Processamento de Pedidos e Gateway de Pagamentos";
    const lang = params.language || "TypeScript";

    const hasAI = !!(process.env.GEMINI_API_KEY || process.env.AI_PROVIDER || params.providerConfig?.apiKey);

    if (hasAI) {
      try {
        const schema = {
          type: "OBJECT",
          properties: {
            title: { type: "STRING" },
            scenario: { type: "STRING" },
            buggySourceCode: { type: "STRING" },
            bugsCatalog: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  bugId: { type: "STRING" },
                  bugType: { type: "STRING", enum: ["SECURITY_VULNERABILITY", "CONCURRENCY_RACE", "OFF_BY_ONE", "RESOURCE_LEAK", "TRANSACTION_INTEGRITY"] },
                  locationHint: { type: "STRING" },
                  explanation: { type: "STRING" },
                  fixSolution: { type: "STRING" }
                },
                required: ["bugId", "bugType", "locationHint", "explanation", "fixSolution"]
              }
            },
            regressionTestCases: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  id: { type: "INTEGER" },
                  input: { type: "STRING" },
                  expectedOutput: { type: "STRING" },
                  catchesBugId: { type: "STRING" }
                },
                required: ["id", "input", "expectedOutput", "catchesBugId"]
              }
            },
            refactoredGoldenSolution: { type: "STRING" },
            rubricCriteria: {
              type: "ARRAY",
              items: {
                type: "OBJECT",
                properties: {
                  criterion: { type: "STRING" },
                  weight: { type: "INTEGER" }
                },
                required: ["criterion", "weight"]
              }
            }
          },
          required: ["title", "scenario", "buggySourceCode", "bugsCatalog", "regressionTestCases", "refactoredGoldenSolution"]
        };

        const optConfig = {
          systemInstruction: "Você é um Engenheiro de Software Sênior e Especialista em Qualidade de Código do SENAI. Crie um desafio de 'Code Bug Hunt' onde um código legado funcional possui exatamente 2 ou 3 falhas críticas sutis (concorrência, segurança, off-by-one ou vazamento) para os alunos auditarem.",
          providerConfig: params.providerConfig
        };

        const promptText = `
Crie um desafio avançado de Bug Hunt & Refactoring:
Tema: ${topic}
Linguagem: ${lang}
Foco: Código realista com 2 a 3 bugs sutis de produção.
`;

        const payload = await aiService.generateStructuredWithRetry<any>(promptText, schema, optConfig);
        if (payload && payload.buggySourceCode && Array.isArray(payload.bugsCatalog)) {
          return {
            id,
            title: payload.title || `Bug Hunt: ${topic}`,
            language: lang,
            scenario: payload.scenario || "Um microsserviço legado está apresentando instabilidade sob carga.",
            buggySourceCode: payload.buggySourceCode,
            totalBugsCount: payload.bugsCatalog.length,
            bugsCatalog: payload.bugsCatalog,
            regressionTestCases: Array.isArray(payload.regressionTestCases) ? payload.regressionTestCases : [],
            refactoredGoldenSolution: payload.refactoredGoldenSolution || "// Solução refatorada",
            rubricCriteria: Array.isArray(payload.rubricCriteria) ? payload.rubricCriteria : [
              { criterion: "Identificação Precisa dos 3 Bugs", weight: 50 },
              { criterion: "Correção e Não-Regressão de Testes", weight: 30 },
              { criterion: "Qualidade de Código e Tipagem", weight: 20 }
            ],
            createdAt: new Date().toISOString()
          };
        }
      } catch (err: any) {
        console.warn("[AdvancedItemBankService] Bug Hunt AI fallback:", err.message);
      }
    }

    // Heuristic Bug Hunt Fallback
    return {
      id,
      title: `Bug Hunt: Transações Concorrentes em ${lang}`,
      language: lang,
      scenario: "Você recebeu o código do módulo de reserva de assentos de uma empresa aérea. O sistema está apresentando overbooking e travamentos em conexões não fechadas.",
      buggySourceCode: `class SeatReservationService {\n  private seats: Map<number, boolean> = new Map();\n  private activePoolConnections = 0;\n\n  async reserveSeat(seatNumber: number, userId: string): Promise<boolean> {\n    this.activePoolConnections++;\n    // BUG 1: Race Condition (Checagem sem Lock antes de gravar)\n    const isTaken = this.seats.get(seatNumber);\n    if (isTaken) {\n      // BUG 2: Resource Leak (Não decrementou activePoolConnections no erro)\n      return false;\n    }\n    \n    await new Promise(r => setTimeout(r, 50)); // Simula I/O assíncrono\n    this.seats.set(seatNumber, true);\n    this.activePoolConnections--;\n    return true;\n  }\n\n  // BUG 3: Off-by-one na contagem de assentos (ignora assento 0)\n  getAvailableSeats(totalSeats: number): number[] {\n    const available: number[] = [];\n    for (let i = 1; i <= totalSeats; i++) {\n      if (!this.seats.get(i)) available.push(i);\n    }\n    return available;\n  }\n}`,
      totalBugsCount: 3,
      bugsCatalog: [
        {
          bugId: "BUG-01",
          bugType: "CONCURRENCY_RACE",
          locationHint: "reserveSeat() nas linhas da checagem assíncrona",
          explanation: "Duas requisições paralelas podem ler isTaken como false simultaneamente antes de gravar o Map, gerando reserva duplicada (Overbooking).",
          fixSolution: "Implementar um Mutex/Semáforo ou atomic check-and-set para garantir exclusão mútua por assento."
        },
        {
          bugId: "BUG-02",
          bugType: "RESOURCE_LEAK",
          locationHint: "Early return quando o assento já está ocupado",
          explanation: "Quando o assento já está ocupado, o método retorna false sem decrementar activePoolConnections, exaurindo o pool.",
          fixSolution: "Utilizar bloco try/finally para garantir que activePoolConnections-- seja executado sempre."
        },
        {
          bugId: "BUG-03",
          bugType: "OFF_BY_ONE",
          locationHint: "getAvailableSeats() no laço for",
          explanation: "O laço inicia em 1 em vez de 0, ignorando o assento de índice zero.",
          fixSolution: "Ajustar o laço para iniciar em let i = 0."
        }
      ],
      regressionTestCases: [
        { id: 1, input: "Concorrência de 2 usuários no assento 5", expectedOutput: "Exatamente 1 true e 1 false", catchesBugId: "BUG-01" },
        { id: 2, input: "Tentativa em assento ocupado", expectedOutput: "activePoolConnections = 0", catchesBugId: "BUG-02" },
        { id: 3, input: "Consulta de total 10 assentos", expectedOutput: "Array com 10 posições (0 a 9)", catchesBugId: "BUG-03" }
      ],
      refactoredGoldenSolution: `class SeatReservationService {\n  private seats: Map<number, boolean> = new Map();\n  private locks: Set<number> = new Set();\n  private activePoolConnections = 0;\n\n  async reserveSeat(seatNumber: number, userId: string): Promise<boolean> {\n    this.activePoolConnections++;\n    try {\n      if (this.locks.has(seatNumber) || this.seats.get(seatNumber)) {\n        return false;\n      }\n      this.locks.add(seatNumber);\n      await new Promise(r => setTimeout(r, 50));\n      this.seats.set(seatNumber, true);\n      return true;\n    } finally {\n      this.locks.delete(seatNumber);\n      this.activePoolConnections--;\n    }\n  }\n\n  getAvailableSeats(totalSeats: number): number[] {\n    const available: number[] = [];\n    for (let i = 0; i < totalSeats; i++) {\n      if (!this.seats.get(i)) available.push(i);\n    }\n    return available;\n  }\n}`,
      rubricCriteria: [
        { criterion: "Correção de Concorrência / Race Condition com Mutex ou Lock", weight: 40 },
        { criterion: "Tratamento de Vazamento de Conexão (try/finally)", weight: 30 },
        { criterion: "Correção de Indexação / Off-by-one", weight: 30 }
      ],
      createdAt: new Date().toISOString()
    };
  }

  // =========================================================================
  // 7. EXPORT ASSEMBLED EXAM BOOKLETS IN SENAI OFFICIAL PDF
  // =========================================================================
  static exportExamBookletToPdf(booklet: AssembledExamBooklet): Buffer {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    // Header SENAI Institucional
    doc.setFillColor(0, 71, 143);
    doc.rect(0, 0, 210, 22, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("SENAI • SERVIÇO NACIONAL DE APRENDIZAGEM INDUSTRIAL", 105, 9, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`AVALIAÇÃO OFICIAL • CADERNO DE PROVA [VERSÃO ${booklet.versionLetter}]`, 105, 16, { align: "center" });

    // Cabeçalho de Identificação do Aluno
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(booklet.examTitle, 14, 30);

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.text(`Curso: ${booklet.courseName} | Turma: ${booklet.classId} | Duração: ${booklet.durationMinutes} min | Total: ${booklet.totalPoints} pts`, 14, 36);

    // Box do Aluno
    doc.setDrawColor(203, 213, 225);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 40, 182, 16, 2, 2, "FD");
    doc.setFontSize(8.5);
    doc.text("Nome do Estudante: __________________________________________________  Matrícula: ________________", 18, 46);
    doc.text("Assinatura: _________________________________________  Data: ____/____/________  Nota: [     /100]", 18, 52);

    let currentY = 62;

    booklet.items.forEach((item, idx) => {
      // Verifica quebra de página
      if (currentY > 250) {
        doc.addPage();
        currentY = 20;
      }

      doc.setFillColor(241, 245, 249);
      doc.rect(14, currentY, 182, 6.5, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text(`QUESTÃO ${item.itemNumber} (${item.points} pts) • ${item.title} [${item.difficulty}]`, 16, currentY + 4.5);
      currentY += 10;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);
      const splitStatement = doc.splitTextToSize(item.statement, 180);
      doc.text(splitStatement, 14, currentY);
      currentY += splitStatement.length * 4.2 + 2;

      // Se tiver alternativas (múltipla escolha)
      if (item.options && item.options.length > 0) {
        item.options.forEach(opt => {
          if (currentY > 270) {
            doc.addPage();
            currentY = 20;
          }
          doc.setFont("helvetica", "bold");
          doc.text(`( ${opt.letter} ) `, 16, currentY);
          doc.setFont("helvetica", "normal");
          const optText = doc.splitTextToSize(opt.text, 165);
          doc.text(optText, 25, currentY);
          currentY += optText.length * 4.2 + 1.5;
        });
      } else {
        // Linhas de resposta para discursiva
        currentY += 2;
        doc.setDrawColor(226, 232, 240);
        for (let l = 0; l < 4; l++) {
          if (currentY > 275) break;
          doc.line(14, currentY, 196, currentY);
          currentY += 5.5;
        }
      }

      currentY += 4;
    });

    // Adiciona Página Final com Gabarito Mestre
    doc.addPage();
    doc.setFillColor(0, 71, 143);
    doc.rect(0, 0, 210, 18, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(`FOLHA DE GABARITO & MATRIZ DE CORREÇÃO • VERSÃO ${booklet.versionLetter}`, 105, 12, { align: "center" });

    const keyRows = booklet.answerKeyMatrix.map(k => [
      `Questão ${k.itemNumber}`,
      k.correctOptionOrSummary,
      `${k.points} pts`
    ]);

    safeAutoTable(doc, {
      startY: 26,
      head: [["Item", "Gabarito Oficial / Padrão de Resposta", "Pontuação"]],
      body: keyRows,
      theme: "striped",
      headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 8.5, fontStyle: "bold" },
      bodyStyles: { fontSize: 8, cellPadding: 2.5 }
    });

    return Buffer.from(doc.output("arraybuffer"));
  }
}

export default AdvancedItemBankService;
